2024-12-02 12:27:36,041 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-02 12:30:47,065 INFO: Ride request for user: 5e757695-8f96-4897-a8da-0f1a3a2ea86f [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:26]
2024-12-02 12:30:47,663 INFO: Ride request created successfully: 703194b8-562e-49ac-baa2-5f63070cd6ac [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:48]
2024-12-02 12:34:32,860 INFO: Ride request for user: 5e757695-8f96-4897-a8da-0f1a3a2ea86f [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:26]
2024-12-02 12:34:32,895 INFO: Ride request created successfully: fb547f20-1ff7-4f07-865c-69fa11c9117f [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:48]
2024-12-02 12:49:54,006 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-02 12:57:31,352 INFO: Ride request for user: f41ecd02-15c8-4de1-98ca-9cf55b677113 [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:26]
2024-12-02 12:57:31,386 INFO: Ride request created successfully: 6749d57f-b9d7-41c0-8a0a-1dc18f4426af [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:48]
2024-12-02 13:01:00,079 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-02 13:09:01,677 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-02 13:09:04,746 INFO: Ride request for user: f41ecd02-15c8-4de1-98ca-9cf55b677113 [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:26]
2024-12-02 13:09:04,789 INFO: Ride request created successfully: 41d3f27a-ebd2-47d7-b3cc-e0b3eaa4caca [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:48]
2024-12-02 13:17:42,609 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-02 13:18:36,594 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-02 13:19:11,419 INFO: Fetching ride status by ID: 41d3f27a-ebd2-47d7-b3cc-e0b3eaa4caca [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:55]
2024-12-02 13:19:11,482 INFO: Ride status: PENDING [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:60]
2024-12-02 13:20:13,042 INFO: Fetching ride status by ID: 41d3f27a-ebd2-47d7-b3cc-e0b3eaa4caca [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:55]
2024-12-02 13:20:13,044 INFO: Ride status: PENDING [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:60]
2024-12-03 18:10:00,991 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-03 19:07:53,200 INFO: Ride request for user: 5e757695-8f96-4897-a8da-0f1a3a2ea86f [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:25]
2024-12-03 19:07:53,270 INFO: Ride request created successfully: d5c2cd6d-38ac-4896-944d-85fc0f7ca21d [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:47]
2024-12-03 19:09:13,131 INFO: Fetching ride status by ID: d5c2cd6d-38ac-4896-944d-85fc0f7ca21d [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:54]
2024-12-03 19:09:13,147 INFO: Ride status: PENDING [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/routes.py:59]
2024-12-03 23:35:49,613 INFO: Application startup [in /Users/andreaamato/git/ride-sharing-app/ride-request-service/app/logger.py:19]
2024-12-08 00:06:02,132 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 00:12:43,016 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 00:15:45,940 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 00:30:32,843 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 10:30:56,048 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 11:12:04,593 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:25]
2024-12-08 11:12:04,631 INFO: Ride request created successfully: e597996f-48f6-479f-97e2-e73d01e196ac [in /app/app/routes.py:47]
2024-12-08 11:23:58,576 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 11:43:15,291 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:25]
2024-12-08 11:43:15,363 INFO: Ride request created successfully: 5c705ea1-464f-41dd-aea1-c778960c9149 [in /app/app/routes.py:47]
2024-12-08 11:45:33,350 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:25]
2024-12-08 11:45:33,371 INFO: Ride request created successfully: caeded77-59c7-42f9-b05c-e0e701a91f66 [in /app/app/routes.py:47]
2024-12-08 11:48:27,239 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 11:52:34,038 WARNING: Token is missing [in /app/app/utils.py:16]
2024-12-08 12:39:17,362 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 12:41:51,439 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 12:44:52,245 WARNING: Token is missing [in /app/app/utils.py:16]
2024-12-08 12:46:39,385 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-08 12:46:39,429 WARNING: Username mismatch during ride request [in /app/app/routes.py:47]
2024-12-08 12:46:50,503 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-08 12:46:50,546 WARNING: Username mismatch during ride request [in /app/app/routes.py:47]
2024-12-08 13:21:20,851 INFO: Ride request for user: dd361060-1cc1-47a8-985e-65ab924e26b2 [in /app/app/routes.py:26]
2024-12-08 13:21:20,896 WARNING: User is not authorized to request rides [in /app/app/routes.py:51]
2024-12-08 23:19:25,781 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 23:21:23,370 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 23:43:15,530 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 23:43:35,273 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 23:52:11,438 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 23:57:31,920 INFO: Application startup [in /app/app/logger.py:19]
2024-12-08 23:59:18,659 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 00:05:22,484 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 00:11:32,894 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 09:34:04,551 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 09:59:35,414 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:20:19,133 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 11:20:19,329 ERROR: Exception on /rides/request [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/utils.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/app/app/routes.py", line 69, in create_ride_request
    current_app.kafka_producer.send(current_app.config['KAFKA_TOPIC'], ride_request)
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 581, in send
    value_bytes = self._serialize(
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/app/app/__init__.py", line 22, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
NameError: name 'json' is not defined
2024-12-09 11:24:48,097 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:27:27,542 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
2024-12-09 11:27:27,651 ERROR: Exception on /rides/request [POST] [in /usr/local/lib/python3.9/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app/utils.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/app/app/routes.py", line 69, in create_ride_request
    current_app.kafka_producer.send(current_app.config['KAFKA_TOPIC'], ride_request)
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 581, in send
    value_bytes = self._serialize(
  File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/app/app/__init__.py", line 22, in <lambda>
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
NameError: name 'json' is not defined
2024-12-09 11:30:40,706 INFO: Application startup [in /app/app/logger.py:19]
2024-12-09 11:33:50,063 INFO: Ride request for user: 0c3c1a7e-1e1b-4709-8320-0a1bcfeafa6d [in /app/app/routes.py:26]
